# Generated by Django 4.2.1 on 2023-05-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argentina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripitem',
            name='warning',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
