# Generated by Django 4.2.1 on 2023-05-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argentina', '0003_alter_tripitem_excursion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripitem',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_item', to='argentina.hotel'),
        ),
    ]
