# Generated by Django 4.2.1 on 2023-05-17 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argentina', '0004_alter_tripitem_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='shared_with',
        ),
        migrations.CreateModel(
            name='SharedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_trip', to='argentina.trip')),
                ('trip_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
