# Generated by Django 4.2.1 on 2023-05-23 14:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('argentina', '0005_remove_trip_shared_with_shareduser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursion',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='attractions_selected',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CITY', 'City'), ('FALLS', 'Falls'), ('MOUNTAINS', 'Mountains'), ('COUNTRYSIDE', 'Countryside'), ('GLACIERS', 'Glaciers'), ('WILDLIFE', 'Wildlife')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='interests_selected',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FOOD', 'Food'), ('MUSIC', 'Music'), ('ART', 'Art'), ('TREKKING', 'Trekking'), ('ACTIVE', 'Active Activities'), ('RELAXING', 'Relaxing'), ('LANDSCAPES', 'Landscapes'), ('NATURE', 'Nature'), ('CULTURE', 'Culture')], max_length=500, null=True),
        ),
    ]
