# Generated by Django 4.0.6 on 2022-10-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argentina', '0006_rename_atractions_destination_attractions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='visited_destinations',
            field=models.ManyToManyField(blank=True, related_name='visited', to='argentina.destination'),
        ),
    ]
