# Generated by Django 4.0.6 on 2023-03-28 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argentina', '0008_alter_destination_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdestination',
            name='excursions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_excursions', to='argentina.tripexcursions'),
        ),
    ]
